engines:
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
  phpcodesniffer:
    enabled: true
    config:
      file_extensions:
        - php
      standard:
        - "PSR2"
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
        - inc
ratings:
  paths:
  - src/*
exclude_paths:
- test/
- vendor/
